#!/bin/bash

# bash train_scripts/disc/shell_scripts/evaluate/her/medium/evaluate_her_by_success_rate.sh &> tmp_her_medium_res.txt

# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_1.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 8234 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_2.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 341 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_3.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 2346 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_4.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 94 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_5.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 164 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_6.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 2436 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_7.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 2487 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_8.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 3593 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_9.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 29826 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/sac/medium_her/sac_config_10hz_128_128_10.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac_only --seed 5289 --n-envs 32 --n-eval-episode 1000

# #---------------------------------------- epsilon = [1.0, 0.3, 0.3] -------------------------------------------------------------
# # epsilon = [1.0, 0.3, 0.3]  regularization_strength = 0.001  N = 16
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_1.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 35210 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_2.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 723 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_3.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 93403 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_4.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 42006 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_5.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 42451 --n-envs 32 --n-eval-episode 1000
python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_6.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 326 --n-envs 32 --n-eval-episode 1000
python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_7.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 2283 --n-envs 32 --n-eval-episode 1000
python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_8.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 348234 --n-envs 32 --n-eval-episode 1000
python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_9.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 52347 --n-envs 32 --n-eval-episode 1000
python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_001_N_16/128_128_seed_10.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 5693 --n-envs 32 --n-eval-episode 1000

# # epsilon = [1.0, 0.3, 0.3]  regularization_strength = 0.0001  N = 16
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_0001_N_16/128_128_seed_1.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 5033 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_0001_N_16/128_128_seed_2.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 178 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_0001_N_16/128_128_seed_3.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 65 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_0001_N_16/128_128_seed_4.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 9008 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0/epsilon_0_1_reg_0_0001_N_16/128_128_seed_5.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 4001 --n-envs 32 --n-eval-episode 1000


# epsilon = [1.0, 0.3, 0.3]  regularization_strength = 0.001  beta = 0.1  N = 16
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_001_N_16/128_128_seed_1.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 3465 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_001_N_16/128_128_seed_2.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 5683 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_001_N_16/128_128_seed_3.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 63456 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_001_N_16/128_128_seed_4.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 7984 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_001_N_16/128_128_seed_5.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 225468 --n-envs 32 --n-eval-episode 1000

# epsilon = [1.0, 0.3, 0.3]  regularization_strength = 0.0001  beta = 0.1  N = 16
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_0001_N_16/128_128_seed_1.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 65223 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_0001_N_16/128_128_seed_2.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 689322 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_0001_N_16/128_128_seed_3.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 2345687 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_0001_N_16/128_128_seed_4.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 68539 --n-envs 32 --n-eval-episode 1000
# python train_scripts/disc/evaluate/evaluate_policy_by_success_rate.py --algo-config-file configs/train/disc/her/medium/beta_0_1/epsilon_0_1_reg_0_0001_N_16/128_128_seed_5.json --env-config-file configs/env/D2D/env_config_for_ppo_medium_b_05.json --algo sac --seed 2435825 --n-envs 32 --n-eval-episode 1000
