#!/bin/bash

#----------------------------------Agerage Adjacent KL--------------------------------------------
# sac without smooth goal  eval: epsilon 0.1
python train_scripts/disc/evaluate/evaluate_sac_with_agerage_adjacent_KL.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-class SAC --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.01 --evaluate-adjacent-num 5 --res-file-save-name train_scripts/disc/plots/sac/results/sac_epsilon_0_reg_0_N_16_noise_0_01.csv

# sac without smooth goal  eval: epsilon 0.1
python train_scripts/disc/evaluate/evaluate_sac_with_agerage_adjacent_KL.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-class SAC --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --evaluate-adjacent-num 5 --res-file-save-name train_scripts/disc/plots/sac/results/sac_epsilon_0_reg_0_N_16_noise_0_1.csv

# sac without smooth goal  eval: epsilon 0.1
python train_scripts/disc/evaluate/evaluate_sac_with_agerage_adjacent_KL.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-class SAC --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --res-file-save-name train_scripts/disc/plots/sac/results/sac_epsilon_0_reg_0_N_16_noise_1.csv


#----------------------------------Gradient Ascent Attacker--------------------------------------------
# sac without smooth goal  eval: epsilon 0.01
python train_scripts/disc/evaluate/evaluate_sac_with_gradient_ascent_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-gradient-ascent-lr 0.0003 --evaluate-gradient-optimization-steps 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.01 --attacker-flag-str Gradient-Ascent[KL]-0.0003-10 --policy-distance-measure-func KL --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_SAC_GA_KL_0_0003_10_noise_0_01.csv

# sac without smooth goal  eval: epsilon 0.1
python train_scripts/disc/evaluate/evaluate_sac_with_gradient_ascent_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-gradient-ascent-lr 0.0003 --evaluate-gradient-optimization-steps 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Gradient-Ascent[KL]-0.0003-10 --policy-distance-measure-func KL --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_SAC_GA_KL_0_0003_10_noise_0_1.csv

# sac without smooth goal  eval: epsilon 0.5
python train_scripts/disc/evaluate/evaluate_sac_with_gradient_ascent_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-gradient-ascent-lr 0.0003 --evaluate-gradient-optimization-steps 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.5 --attacker-flag-str Gradient-Ascent[KL]-0.0003-10 --policy-distance-measure-func KL --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_SAC_GA_KL_0_0003_10_noise_0_5.csv

# sac without smooth goal  eval: epsilon 1.0
python train_scripts/disc/evaluate/evaluate_sac_with_gradient_ascent_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-gradient-ascent-lr 0.0003 --evaluate-gradient-optimization-steps 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --attacker-flag-str Gradient-Ascent[KL]-0.0003-10 --policy-distance-measure-func KL --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_SAC_GA_KL_0_0003_10_noise_1.csv


#----------------------------------Random Attacker--------------------------------------------
# sac without smooth goal  eval: epsilon 0.01
python train_scripts/disc/evaluate/evaluate_sac_with_random_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.01 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_sac_random_10_noise_0_01.csv

# sac without smooth goal  eval: epsilon 0.1
python train_scripts/disc/evaluate/evaluate_sac_with_random_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_sac_random_10_noise_0_1.csv

# sac without smooth goal  eval: epsilon 0.5
python train_scripts/disc/evaluate/evaluate_sac_with_random_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.5 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_sac_random_10_noise_0_5.csv

# sac without smooth goal  eval: epsilon 1.0
python train_scripts/disc/evaluate/evaluate_sac_with_random_attacker.py --env-config configs/env/D2D/env_config_for_ppo_medium_b_05.json --env-flag-str Medium-05 --algo-ckpt-dir checkpoints/rl_single/sac_medium_128_128_1e6steps_loss_{0}_singleRL --algo-ckpt-model-name best_model --algo-seeds 1 2 3 4 5 --algo-flag-str SAC --algo-epsilon 0.0 --algo-reg 0.0 --evaluate-dg-num 300 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/sac/N_16/res_log_medium_sac_random_10_noise_1.csv
