#!/bin/bash


#--------------------------------------------------------------------PPO--------------------------------------------------------------
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/MSR/env_config_for_ppo_10hz_medium_b_05.json --env-flag-str Medium-05 --algo-class PPO --algo-ckpt-dir checkpoints/IRPO/rl_single/ppo_medium_128_128_2e8steps_{0}_singleRL --algo-seeds 1 2 3 4 5 --algo-flag-str PPO --algo-epsilon 0.0 --algo-reg 0.0 --algo-reg-beta 0.0 --algo-v-reg 0.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/ppo_eval_noise_1.csv

## from pre-trained (IRPO iter1 lambda=0.001)   eval: epsilon 1.0
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/IRPO/env_hard_guidance_MR_config_for_ppo.json --env-flag-str Hard-05 --algo-class PPO --algo-ckpt-dir checkpoints/IRPO/rl/guidance_law_mode/iter_1/128_128_2e8steps_lambda_1e-3_{0} --algo-seeds 1 2 3 4 5 --algo-flag-str PPO --algo-epsilon 0.0 --algo-reg 0.0 --algo-reg-beta 0.0 --algo-v-reg 0.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/IRPO_iter_1_lambda_1e-3_eval_noise_1.csv


#--------------------------------------------------------------------SmoothGoalPPO pi--------------------------------------------------------------
# algo: epsilon 0.1 reg 0.001 beta 0.0   eval: epsilon 1.0
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/MSR/env_config_for_ppo_10hz_medium_b_05.json --env-flag-str Medium-05 --algo-class SmoothGoalPPO --algo-ckpt-dir checkpoints/msr/medium/smooth_goal_ppo_pi/epsilon_0_1_reg_0_001_N_16/128_128_2e8steps_seed_{0} --algo-seeds 1 2 3 4 5 --algo-flag-str SmoothGoalPPO_PI --algo-epsilon 0.1 --algo-reg 0.001 --algo-reg-beta 0.0 --algo-v-reg 0.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/smooth_goal_ppo_pi__epsilon_0_1_reg_0_001_beta_0_eval_noise_1.csv



#--------------------------------------------------------------------SmoothGoalPPO v--------------------------------------------------------------
# algo: epsilon 0.1 v_reg 10 beta 0.0   eval: epsilon 1.0
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/MSR/env_config_for_ppo_10hz_medium_b_05.json --env-flag-str Medium-05 --algo-class SmoothGoalPPO --algo-ckpt-dir checkpoints/msr/medium/smooth_goal_ppo_v/epsilon_0_1_reg_0_001_beta_0_N_16_v_reg_10_v_beta_0/128_128_2e8steps_seed_{0} --algo-seeds 1 2 3 4 5 --algo-flag-str SmoothGoalPPO_V --algo-epsilon 0.1 --algo-reg 0.0 --algo-reg-beta 0.0 --algo-v-reg 10.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/smooth_goal_ppo_v__epsilon_0_1_v_reg_10_v_beta_0_eval_noise_1.csv

# algo: epsilon 0.1 v_reg 100 beta 0.0   eval: epsilon 1.0
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/MSR/env_config_for_ppo_10hz_medium_b_05.json --env-flag-str Medium-05 --algo-class SmoothGoalPPO --algo-ckpt-dir checkpoints/msr/medium/smooth_goal_ppo_v/epsilon_0_1_reg_0_001_beta_0_N_16_v_reg_100_v_beta_0/128_128_2e8steps_seed_{0} --algo-seeds 1 2 3 4 5 --algo-flag-str SmoothGoalPPO_V --algo-epsilon 0.1 --algo-reg 0.0 --algo-reg-beta 0.0 --algo-v-reg 100.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/smooth_goal_ppo_v__epsilon_0_1_v_reg_100_v_beta_0_eval_noise_1.csv



#--------------------------------------------------------------------SmoothGoalPPO pi_and_v--------------------------------------------------------------
# algo: epsilon 0.1 reg 0.001 beta 0.0 v_reg 10 beta 0.0   eval: epsilon 1.0
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/MSR/env_config_for_ppo_10hz_medium_b_05.json --env-flag-str Medium-05 --algo-class SmoothGoalPPO --algo-ckpt-dir checkpoints/msr/medium/smooth_goal_ppo_pi_and_v/epsilon_0_1_reg_0_001_beta_0_N_16_v_reg_10_v_beta_0/128_128_2e8steps_seed_{0} --algo-seeds 1 2 3 4 5 --algo-flag-str SmoothGoalPPO_PI_and_V --algo-epsilon 0.1 --algo-reg 0.001 --algo-reg-beta 0.0 --algo-v-reg 10.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/smooth_goal_ppo_pi_and_v__epsilon_0_1_reg_0_001_beta_0_v_reg_10_v_beta_0_eval_noise_1.csv

# algo: epsilon 0.1 reg 0.001 beta 0.0 v_reg 100 beta 0.0   eval: epsilon 1.0
python train_scripts/msr/evaluate/evaluate_ppo_with_average_adjacent_KL_and_V.py --env-config configs/env/MSR/env_config_for_ppo_10hz_medium_b_05.json --env-flag-str Medium-05 --algo-class SmoothGoalPPO --algo-ckpt-dir checkpoints/msr/medium/smooth_goal_ppo_pi_and_v/epsilon_0_1_reg_0_001_beta_0_N_16_v_reg_100_v_beta_0/128_128_2e8steps_seed_{0} --algo-seeds 1 2 3 4 5 --algo-flag-str SmoothGoalPPO_PI_and_V --algo-epsilon 0.1 --algo-reg 0.001 --algo-reg-beta 0.0 --algo-v-reg 100.0 --algo-v-reg-beta 0.0 --evaluate-dg-num 100 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 1.0 --evaluate-adjacent-num 5 --evaluation-gamma 0.995 --res-file-save-name train_scripts/msr/plots/smooth_goal_ppo/results_KL_and_V/smooth_goal_ppo_pi_and_v__epsilon_0_1_reg_0_001_beta_0_v_reg_100_v_beta_0_eval_noise_1.csv
