#!/bin/bash

# IRPO
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/IRPO/iter1/10hz_128_128_2e8steps_train_with_all_tasks_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 2 3 4 5 --algo-flag-str IRPO_Iter_1 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_IRPO_Iter_1_random_10_noise_0_1.csv
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/IRPO/iter2/10hz_128_128_5e8steps_train_with_all_tasks_lambda_1e-1_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 1 2 4 --algo-flag-str IRPO_Iter_2 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_IRPO_Iter_2_random_10_noise_0_1.csv
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/IRPO/iter3/10hz_256_256_128_128_64_5e8steps_train_with_all_tasks_lambda_1e-1_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 6 8 10 --algo-flag-str IRPO_Iter_3 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_IRPO_Iter_3_random_10_noise_0_1.csv
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/IRPO/iter4/10hz_256_256_128_128_64_5e8steps_train_with_all_tasks_lambda_1e-1_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 1 2 7 --algo-flag-str IRPO_Iter_4 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_IRPO_Iter_4_random_10_noise_0_1.csv

# GCPO
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/GCPO/10hz_128_128_2e8steps_sample_goal_rig_3_09_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 2 3 4 5 --algo-flag-str GCPO_RIG_3_09 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_GCPO_RIG_random_10_noise_0_1.csv
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/GCPO/10hz_128_128_2e8steps_sample_goal_discern_3_09_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 2 3 4 5 --algo-flag-str GCPO_DISCERN_3_09 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_GCPO_DISCERN_random_10_noise_0_1.csv
python train_scripts/disc/evaluate_ppo_with_random_attacker.py --env-config configs/env/env_config_for_ppo.json --env-flag-str HARD --algo-ckpt-dir checkpoints/GCPO/10hz_128_128_2e8steps_sample_goal_mega_3_09_loss_{0} --algo-ckpt-model-name best_model --algo-seeds 2 3 4 5 --algo-flag-str GCPO_MEGA_3_09 --evaluate-dg-num 1000 --evaluate-random-noise-num 10 --evaluate-noise-base 10.0 3.0 3.0 --evaluate-noise-multiplier 0.1 --attacker-flag-str Random --res-file-save-name train_scripts/disc/evaluate/results/res_log_GCPO_MEGA_random_10_noise_0_1.csv